#!/bin/bash


git config --global user.email "99791182@163.com"
git config --global user.name "oabo"

git init
git add .
git commit -m "first commit"
git branch -M www-info
git remote add origin https://github.com/oabo/www.git
git push -u origin www-info
